Update plugin version
HotelsDotCom/hotels-oss-plugin-config pull request #5
Opened 2018-07-04 16:22 UTC by AnanaMJ

resolve #4

2018-07-04 17:23 UTC, massdosage requested changes
You need to add a line to the CHANGELOG describing this (small) change.

2018-07-04 17:23 UTC, massdosage commented on pom.xml
> +  <version>1.1.2-SNAPSHOT</version>
You can leave this as it was, after a release Maven automatically updates the version to the next candidate release version. The last release was 1.1.0 (you can refer to the CHANGELOG) so 1.1.1-SNAPSHOT is correct.

2018-07-06 13:30 UTC, massdosage approved these changes
Looks good. When you have 1 more approval and do a merge make sure you add a merge commit comment that says "Fixes #4" so that Github links things up correctly.

2018-07-09 09:41 UTC, ddcprg approved these changes

2018-07-09 14:01 UTC, merged